name: Release

on:
  push:
    branches:
      - master

jobs:
  push-to-sleuth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Call sleuth
        env:
          SLEUTH_TOKEN: ${{ secrets.SLEUTH_STAGING_API_TOKEN }}
        run: |
          pipenv run app.py \
            -k $SLEUTH_TOKEN \
            -o sleuth \
            -d sleuth-client \
            --commit-url-pattern https://github.com/sleuth-io/sleuth-client/commit/REVISION \
            --file-url-pattern https://github.com/sleuth-io/sleuth-client/blob/REVISION/PATH \
            --baseurl https://staging.sleuth.io