name: Release

on:
  push:
    branches:
      - master

jobs:
  push-to-sleuth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Cache pip
        uses: actions/cache@v2
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install pipenv and deps
        run: |
          python3 -m pip install --upgrade pipenv wheel
          pipenv --python python3.8
          pipenv install --dev
      - name: Call sleuth
        env:
          SLEUTH_TOKEN: ${{ secrets.SLEUTH_STAGING_API_KEY }}
        run: |
          pipenv run python app.py \
            -k $SLEUTH_TOKEN \
            -o sleuth \
            -d sleuth-client \
            --commit-url-pattern https://github.com/sleuth-io/sleuth-client/commit/REVISION \
            --file-url-pattern https://github.com/sleuth-io/sleuth-client/blob/REVISION/PATH \
            --baseurl https://staging.sleuth.io