name: Release

on:
  push:
    branches:
      - master

jobs:
  push-to-sleuth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Cache pip
        uses: actions/cache@v2
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('setup.cfg') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install pipenv and deps
        run: |
          python3 -m pip install --upgrade wheel
          make pyenv
      - name: Generate binary
        run: |
          make dist
      - name: Call sleuth
        env:
          SLEUTH_TOKEN: ${{ secrets.SLEUTH_STAGING_API_KEY }}
        run: |
          venv/bin/sleuth \
            -k $SLEUTH_TOKEN \
            --baseurl https://staging.sleuth.io \
            deploy \
            -o sleuth \
            -d sleuth-client \
            -e staging \
            --commit-url-pattern https://github.com/sleuth-io/sleuth-client/commit/REVISION \
            --file-url-pattern https://github.com/sleuth-io/sleuth-client/blob/REVISION/PATH \
      - name: Create github release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/sleuth
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
